services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: devopsdb
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  app:
    build: .
    image: devops-app:1.2
    ports:
      - "9090:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/devopsdb
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      mysql:
       condition: service_healthy

volumes:
  mysql-data: